name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # 사용할 Ruby 버전을 설정하세요
    - name: Install dependencies
      run: |
        bundle install
    - name: Build and serve
      run: |
        bundle exec jekyll build
